const express = require('express')
const app = express()
const about = require('./aboutus.js')
const contact = require('./contact.js')
const feature = require('./feature.js')
const details = require('./details.js')
const members = require('./members.js')
const service = require('./services.js')
app.get('/',(request,response)=>{
    response.send("Im Home page")

})
app.use('/about',about)
app.use('/contact',contact)
app.use('/feature',feature)
app.use('/details',details)
app.use('/members',members)
app.use('/service',service)
app.listen(3600)